//! wgpu rendering layer for oxcraft: sky, terrain, water, block-outline and
//! UI pipelines sharing one texture atlas generated by [`ox_core`].
//!
//! Shaders are embedded from `shaders/*.wgsl` via `include_str!`; a shader
//! edit therefore only takes effect after a rebuild.

use std::sync::Arc;

use glam::Mat4;
use ox_core::mesher::ChunkMesh;
use ox_core::particles::Particle;

mod chunks;
mod gpu;
mod pass;
mod readback;
use chunks::ChunkStore;
use gpu::Gpu;
pub use pass::crack::CrackParams;
pub use pass::hand::HandParams;
pub use pass::ui;
pub use ui::{ListScroll, MenuButton, Overlay, Rect, UiState, controls_scroll, menu_button};
use wgpu::{Surface, SurfaceConfiguration};

/// Per-frame view and atmosphere parameters uploaded to every pipeline.
///
/// Matrices are column-major `[f32; 4]; 4]` arrays ready for direct upload.
pub struct FrameParams<'a> {
    /// View-projection matrix.
    pub view_proj: [[f32; 4]; 4],
    /// Inverse view-projection, used by the sky shader to reconstruct rays.
    pub inv_view_proj: [[f32; 4]; 4],
    /// Camera position in world space.
    pub cam_pos: [f32; 3],
    /// Normalized direction toward the sun.
    pub sun_dir: [f32; 3],
    /// Sun tint, linear RGB.
    pub sun_color: [f32; 3],
    /// Sky zenith color.
    pub zenith: [f32; 3],
    /// Sky horizon color, also used as fog/clear color.
    pub horizon: [f32; 3],
    /// World position of the block highlighted by the targeting outline.
    pub highlight: Option<[i32; 3]>,
    /// Fog start distance in blocks.
    pub fog_near: f32,
    /// Fog end distance in blocks.
    pub fog_far: f32,
    /// First-person hand contents and swing phase; `None` hides the hand.
    pub hand: Option<HandParams>,
    /// Block under attack and how far along its break is, if any.
    pub crack: Option<CrackParams>,
    /// Live block debris drawn as camera-facing squares.
    pub particles: &'a [Particle],
}

/// Owns the GPU device, the optional presentation surface, the pipelines and
/// the per-chunk buffers.
pub struct Renderer {
    gpu: Gpu,
    surface: Option<Surface<'static>>,
    config: SurfaceConfiguration,
    depth_view: Option<wgpu::TextureView>,
    sky: pass::SkyPass,
    terrain: pass::TerrainPass,
    particles: pass::ParticlesPass,
    crack: pass::CrackPass,
    outline: pass::OutlinePass,
    hand: pass::HandPass,
    chunks: ChunkStore,
    ui: pass::UiPass,
}

/// Pixel format of the headless render target: RGBA8, so [`Renderer::capture`]
/// writes it to PNG without a swizzle.
const HEADLESS_FORMAT: wgpu::TextureFormat = wgpu::TextureFormat::Rgba8Unorm;

async fn request_device(adapter: &wgpu::Adapter) -> Result<(wgpu::Device, wgpu::Queue), String> {
    adapter
        .request_device(&wgpu::DeviceDescriptor {
            label: Some("oxcraft-device"),
            required_features: wgpu::Features::empty(),
            required_limits: wgpu::Limits::default(),
            memory_hints: wgpu::MemoryHints::default(),
            trace: wgpu::Trace::Off,
            experimental_features: wgpu::ExperimentalFeatures::default(),
        })
        .await
        .map_err(|e| e.to_string())
}

impl Renderer {
    /// Creates a renderer presenting to `window`, picking the first non-sRGB
    /// surface format and a high-performance adapter.
    ///
    /// # Errors
    ///
    /// Returns an error string when no compatible adapter/device can be
    /// created or the surface cannot be initialized; the process should
    /// treat this as fatal since there is nothing to render without a GPU.
    pub async fn windowed(
        display: impl raw_window_handle::HasDisplayHandle + std::fmt::Debug + Send + Sync + 'static,
        window: Arc<winit::window::Window>,
    ) -> Result<Self, String> {
        let size = window.inner_size();
        let instance = wgpu::Instance::new(wgpu::InstanceDescriptor::new_with_display_handle(
            Box::new(display),
        ));
        let surface = instance
            .create_surface(window.clone())
            .map_err(|e| e.to_string())?;
        let adapter = instance
            .request_adapter(&wgpu::RequestAdapterOptions {
                power_preference: wgpu::PowerPreference::HighPerformance,
                compatible_surface: Some(&surface),
                force_fallback_adapter: false,
            })
            .await
            .map_err(|e| e.to_string())?;
        let (device, queue) = request_device(&adapter).await?;
        let caps = surface.get_capabilities(&adapter);
        let format = caps
            .formats
            .iter()
            .copied()
            .find(|f| !f.is_srgb())
            .unwrap_or(caps.formats[0]);
        let config = SurfaceConfiguration {
            usage: wgpu::TextureUsages::RENDER_ATTACHMENT,
            format,
            width: size.width.max(1),
            height: size.height.max(1),
            present_mode: wgpu::PresentMode::Fifo,
            alpha_mode: caps.alpha_modes[0],
            view_formats: vec![],
            desired_maximum_frame_latency: 2,
        };
        surface.configure(&device, &config);
        Ok(Self::build(device, queue, Some(surface), config))
    }

    /// Creates a renderer without a surface that draws `width` x `height`
    /// offscreen frames; [`Renderer::capture`] is its only output.
    ///
    /// The adapter follows `WGPU_ADAPTER_NAME` and `WGPU_BACKEND` when set
    /// (`WGPU_ADAPTER_NAME=llvmpipe` selects Mesa's software Vulkan driver)
    /// and is the default adapter otherwise.
    ///
    /// # Errors
    ///
    /// Returns an error string when no adapter or device is available.
    pub async fn headless(width: u32, height: u32) -> Result<Self, String> {
        let instance =
            wgpu::Instance::new(wgpu::InstanceDescriptor::new_without_display_handle_from_env());
        let adapter = wgpu::util::initialize_adapter_from_env_or_default(&instance, None)
            .await
            .map_err(|e| e.to_string())?;
        let (device, queue) = request_device(&adapter).await?;
        let config = SurfaceConfiguration {
            usage: wgpu::TextureUsages::RENDER_ATTACHMENT,
            format: HEADLESS_FORMAT,
            width: width.max(1),
            height: height.max(1),
            present_mode: wgpu::PresentMode::Fifo,
            alpha_mode: wgpu::CompositeAlphaMode::Auto,
            view_formats: vec![],
            desired_maximum_frame_latency: 2,
        };
        Ok(Self::build(device, queue, None, config))
    }

    /// Builds every pipeline and shared resource for `config.format`.
    fn build(
        device: wgpu::Device,
        queue: wgpu::Queue,
        surface: Option<Surface<'static>>,
        config: SurfaceConfiguration,
    ) -> Self {
        let format = config.format;
        let gpu = Gpu::new(device, queue);

        let sky = pass::SkyPass::new(&gpu, format);
        let terrain = pass::TerrainPass::new(&gpu, format);
        let particles = pass::ParticlesPass::new(&gpu, format);
        let crack = pass::CrackPass::new(&gpu, format);
        let outline = pass::OutlinePass::new(&gpu, format);
        let hand = pass::HandPass::new(&gpu, format);
        let ui = pass::UiPass::new(&gpu, format);
        let mut renderer = Self {
            gpu,
            surface,
            config,
            depth_view: None,
            sky,
            terrain,
            particles,
            crack,
            outline,
            hand,
            chunks: ChunkStore::new(),
            ui,
        };
        renderer.recreate_depth();
        renderer
    }

    fn recreate_depth(&mut self) {
        let depth = self.gpu.device.create_texture(&wgpu::TextureDescriptor {
            label: Some("depth"),
            size: wgpu::Extent3d {
                width: self.config.width,
                height: self.config.height,
                depth_or_array_layers: 1,
            },
            mip_level_count: 1,
            sample_count: 1,
            dimension: wgpu::TextureDimension::D2,
            format: wgpu::TextureFormat::Depth24Plus,
            usage: wgpu::TextureUsages::RENDER_ATTACHMENT,
            view_formats: &[],
        });
        self.depth_view = Some(depth.create_view(&wgpu::TextureViewDescriptor::default()));
    }

    /// Reconfigures the surface for a new size and rebuilds the depth
    /// buffer; zero sizes are ignored (minimized window).
    pub fn resize(&mut self, width: u32, height: u32) {
        if width == 0 || height == 0 {
            return;
        }
        self.config.width = width;
        self.config.height = height;
        if let Some(surface) = &self.surface {
            surface.configure(&self.gpu.device, &self.config);
        }
        self.recreate_depth();
    }

    /// Render target size in pixels.
    #[must_use]
    pub const fn size(&self) -> (u32, u32) {
        (self.config.width, self.config.height)
    }

    /// Uploads or replaces the GPU buffers for one chunk's mesh.
    pub fn upload_chunk(&mut self, key: (i32, i32), mesh: &ChunkMesh) {
        self.chunks.upload(&self.gpu, key, mesh);
    }

    /// Builds and uploads the UI geometry the next frame will draw. Call it
    /// before `draw` or `capture`: those only record what is already in the
    /// buffers, so a skipped call redraws the previous frame's overlay.
    pub fn prepare_ui(&mut self, ui: Option<&ui::UiState<'_>>) {
        let (width, height) = (self.config.width as f32, self.config.height as f32);
        self.ui.prepare(&self.gpu.queue, ui, width, height);
    }

    /// Drops a chunk's GPU buffers.
    pub fn remove_chunk(&mut self, key: (i32, i32)) {
        self.chunks.remove(key);
    }

    /// Coordinates of every chunk currently resident on the GPU.
    pub fn meshed_chunks(&self) -> impl Iterator<Item = (i32, i32)> + '_ {
        self.chunks.keys()
    }

    /// Renders one frame to the swap chain and presents it.
    ///
    /// # Errors
    ///
    /// Returns an error string when the renderer is headless or the surface
    /// cannot provide a texture (e.g. the window is minimized or the device
    /// was lost).
    pub fn draw(
        &self,
        frame: &FrameParams<'_>,
        ui: Option<&ui::UiState<'_>>,
    ) -> Result<(), String> {
        let Some(surface) = &self.surface else {
            return Err("headless renderer has no surface to present to".to_string());
        };
        let texture = match surface.get_current_texture() {
            wgpu::CurrentSurfaceTexture::Success(t)
            | wgpu::CurrentSurfaceTexture::Suboptimal(t) => t,
            other => return Err(format!("surface unavailable: {other:?}")),
        };
        let view = texture
            .texture
            .create_view(&wgpu::TextureViewDescriptor::default());
        self.render_frame(&view, frame, ui);
        texture.present();
        Ok(())
    }

    /// Renders one frame into an offscreen texture and writes it to `path`
    /// as an RGBA PNG (BGRA surfaces are swizzled); used by the headless
    /// screenshot and test-server modes.
    ///
    /// # Errors
    ///
    /// Returns an error string when the frame cannot be rendered or the
    /// GPU-to-CPU copy fails.
    pub fn capture(
        &self,
        frame: &FrameParams<'_>,
        ui: Option<&ui::UiState<'_>>,
        path: &str,
    ) -> Result<(), String> {
        let w = self.config.width;
        let h = self.config.height;
        let tex = self.gpu.device.create_texture(&wgpu::TextureDescriptor {
            label: Some("capture-target"),
            size: wgpu::Extent3d {
                width: w,
                height: h,
                depth_or_array_layers: 1,
            },
            mip_level_count: 1,
            sample_count: 1,
            dimension: wgpu::TextureDimension::D2,
            format: self.config.format,
            usage: wgpu::TextureUsages::RENDER_ATTACHMENT | wgpu::TextureUsages::COPY_SRC,
            view_formats: &[],
        });
        let view = tex.create_view(&wgpu::TextureViewDescriptor::default());
        self.render_frame(&view, frame, ui);
        readback::save_png(&self.gpu, &tex, w, h, self.config.format, path)
    }

    /// The depth attachment for one pass; `load` either clears it or keeps
    /// what the previous pass stored.
    const fn depth_attachment(
        &self,
        load: wgpu::LoadOp<f32>,
    ) -> wgpu::RenderPassDepthStencilAttachment<'_> {
        #[expect(
            clippy::expect_used,
            reason = "depth buffer is recreated in build() and on every resize"
        )]
        let view = self.depth_view.as_ref().expect("depth initialized");
        wgpu::RenderPassDepthStencilAttachment {
            view,
            depth_ops: Some(wgpu::Operations {
                load,
                store: wgpu::StoreOp::Store,
            }),
            stencil_ops: None,
        }
    }

    /// Records and submits the frame's render passes into `view`.
    fn render_frame(
        &self,
        view: &wgpu::TextureView,
        frame: &FrameParams<'_>,
        ui: Option<&ui::UiState<'_>>,
    ) {
        let mut encoder = self
            .gpu
            .device
            .create_command_encoder(&wgpu::CommandEncoderDescriptor { label: None });
        {
            let mut rpass = encoder.begin_render_pass(&wgpu::RenderPassDescriptor {
                label: Some("main"),
                color_attachments: &[Some(wgpu::RenderPassColorAttachment {
                    view,
                    resolve_target: None,
                    ops: wgpu::Operations {
                        load: wgpu::LoadOp::Clear(wgpu::Color {
                            r: f64::from(frame.horizon[0]),
                            g: f64::from(frame.horizon[1]),
                            b: f64::from(frame.horizon[2]),
                            a: 1.0,
                        }),
                        store: wgpu::StoreOp::Store,
                    },
                    depth_slice: None,
                })],
                depth_stencil_attachment: Some(self.depth_attachment(wgpu::LoadOp::Clear(1.0))),
                timestamp_writes: None,
                occlusion_query_set: None,
                multiview_mask: None,
            });

            self.sky.record(
                &mut rpass,
                &self.gpu.queue,
                frame,
                self.config.width as f32,
                self.config.height as f32,
            );

            self.terrain
                .record(&mut rpass, &self.gpu.queue, frame, &self.chunks);

            self.particles.record(&mut rpass, &self.gpu.queue, frame);

            self.crack.record(&mut rpass, &self.gpu.queue, frame);

            self.outline.record(&mut rpass, &self.gpu.queue, frame);
        }
        {
            let mut rpass = encoder.begin_render_pass(&wgpu::RenderPassDescriptor {
                label: Some("overlay"),
                color_attachments: &[Some(wgpu::RenderPassColorAttachment {
                    view,
                    resolve_target: None,
                    ops: wgpu::Operations {
                        load: wgpu::LoadOp::Load,
                        store: wgpu::StoreOp::Store,
                    },
                    depth_slice: None,
                })],
                depth_stencil_attachment: Some(self.depth_attachment(wgpu::LoadOp::Clear(1.0))),
                timestamp_writes: None,
                occlusion_query_set: None,
                multiview_mask: None,
            });

            self.hand.record(
                &mut rpass,
                &self.gpu.queue,
                frame,
                self.config.width as f32,
                self.config.height as f32,
            );

            self.ui.record(
                &mut rpass,
                ui,
                self.config.width as f32,
                self.config.height as f32,
            );
        }
        self.gpu.queue.submit([encoder.finish()]);
    }
}

/// Builds a right-handed view-projection matrix and its inverse for the
/// given camera parameters; near plane is fixed at 0.1.
#[must_use]
pub fn perspective_view(
    eye: [f32; 3],
    yaw: f32,
    pitch: f32,
    aspect: f32,
    fov_deg: f32,
    far: f32,
) -> ([[f32; 4]; 4], [[f32; 4]; 4]) {
    let proj = glam::camera::rh::proj::directx::perspective(fov_deg.to_radians(), aspect, 0.1, far);
    let view = Mat4::from_rotation_x(-pitch)
        * Mat4::from_rotation_y(-yaw)
        * Mat4::from_translation(-glam::Vec3::from(eye));
    let vp = proj * view;
    (vp.to_cols_array_2d(), vp.inverse().to_cols_array_2d())
}
