[package]
name = "ox-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license = "MIT"
description = "oxcraft binary: winit event loop, streaming and game shell."

[[bin]]
name = "oxcraft"
path = "src/main.rs"

[dependencies]
ox-core = { path = "../core" }
ox-render = { path = "../render" }
winit = "0.30"
pollster = "1"
cpal = "0.18"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"

[lints]
workspace = true
